import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { Box } from '@mui/material';

type Language = 'English' | 'Urdu' | 'Arabic';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    /**
     * Looks up a phrase, substituting `{name}` placeholders from `vars`. The
     * argument is optional, so phrases without placeholders read as before.
     */
    t: (key: string, vars?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
    'English': {
        'welcome': 'Welcome to EDXS',
        'select_org': 'Please select your organization type to proceed',
        'enterprise_solutions': 'Enterprise Solutions v3.0',
        'change_language': 'Change Language',
        'save': 'Save',
        'cancel': 'Cancel',
        'select_language': 'Select Language',
        'school': 'School',
        'school_subtitle': 'K-12 Education Suite',
        'school_desc': 'Comprehensive management for students, exams, and daily attendance.',
        'college': 'College',
        'college_subtitle': 'Academic & Vocational',
        'college_desc': 'Streamline admissions, faculty workflows, and course scheduling.',
        'university': 'University',
        'univ_subtitle': 'Global Campus ERP',
        'univ_desc': 'Advanced unification for multi-campus research and administration.',
        'training': 'Professional Training',
        'training_subtitle': 'Vocational & Skills',
        'training_desc': 'Advanced workflows for corporate training and skill development centers.',
        'corporate': 'Corporate Solutions',
        'corp_subtitle': 'Enterprise Business Suite',
        'corp_desc': 'Scalable management for workforce training, corporate academies, and business operations.',
        'enter_module': 'ENTER MODULE',
        'back_to_selection': 'Back to Selection',
        'back': 'Back',
        'next': 'Next',
        'basic_information': 'Basic Information',
        'please_provide_the_following_details_to_set_up_your': 'Please provide the following details to set up your',
        'contact_person_name': 'Contact Person Name',
        'designation': 'Designation',
        'email_address': 'Email Address',
        'cell_phone_number': 'Cell Phone Number',
        'landline_number': 'Landline Number',
        'website': 'Website',
        'address': 'Address',
        'street_address': 'Street Address',
        'city': 'City',
        'state_province': 'State/Province',
        'postal_code': 'Postal Code',
        'karachi': 'Karachi',
        'sindh': 'Sindh',
        '75500': '75500',
        'organization_setup': 'Organization Setup',
        'configure_the_core_settings_and_branding_for_your': 'Configure the core settings and branding for your',
        'core_settings': 'Core Settings',
        'organization_code': 'Organization Code',
        'fiscal_year': 'Fiscal Year',
        'curriculum': 'Curriculum',
        'curriculum_placeholder': 'e.g. O-Levels, SSC, Cambridge',
        'affiliation_board': 'Affiliation Board',
        'affiliation_placeholder': 'e.g. BIEK, BISE',
        'hec_id_registration_no': 'HEC ID / Registration No.',
        'hec_id_placeholder': 'e.g. UNIV-2024-001',
        'branding': 'Branding',
        'upload_logo': 'Upload Logo',
        'drag_and_drop_your_logo_here': 'Drag and drop your logo here',
        'or_click_to_browse': 'or click to browse',
        'drag_and_drop_or_click_to_browse': 'Drag and drop, or click to browse',
        'supported_formats': 'Supported formats: PNG, JPG (Max 2MB)',
        'remove_logo': 'Remove Logo',
        'click_to_change_logo': 'Click to change logo',
        'complete_setup': 'Complete Setup',
        'all_set': 'All Set!',
        'configuration_complete': 'Configuration Complete!',
        'your_organization_has_been_successfully_configured': 'Your organization has been successfully configured.',
        'details': 'Details',
        'information': 'Information',
        'name': 'Name',
        'all_rights_reserved': 'All rights reserved',
        'key_features': 'Key Features',
        'visibility': 'Visibility',
        'branding_logo': 'Logo & Branding',
        'please_fill_required_fields': 'Please fill in the required fields correctly',
        'valid_email_address': 'Valid Email Address',
        'redirecting_to_dashboard': 'Redirecting to dashboard...',
        'redirecting_to_selection': 'Redirecting to selection...',
        'validation_required': 'Validation Required',
        'select_our': 'Select your',
        'organization_type': 'Organization Type',
        'get_started_desc': 'Choose the setup that matches your institution to get started.',
        'start_your_free_trial': 'Start your free trial',
        'trial_form_intro': 'Create your organization and your login. Setup takes a minute, and no credit card is needed.',
        'trial_disclaimer_title': 'This is a {days}-day free trial',
        'trial_disclaimer_body': 'Your account is a free trial for {days} days and expires on {date}. To keep going after that, contact us to upgrade. Please do not enter live production data during the trial.',
        'trial_footer_note': 'By starting, you acknowledge this is a {days}-day trial account.',
        'organization_details': 'Organization Details',
        'contact_detail': 'Contact Detail',
        'your_login': 'Your Login',
        'your_login_hint': 'These are the details you will sign in to EDXS with once the trial is created.',
        'client_name': 'Organization Name',
        'client_name_placeholder': 'e.g. Horizon School',
        'campus_name': 'Campus Name',
        'campus_name_placeholder': 'e.g. Main Campus',
        'description': 'Description',
        'contact_person': 'Contact Person',
        'contact_no': 'Contact No',
        'mobile': 'Mobile',
        'country': 'Country',
        'state': 'State',
        'username': 'Username',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'full_name': 'Full Name',
        'show_password': 'Show password',
        'hide_password': 'Hide password',
        'module_access': 'Module Access',
        'module_access_hint': 'Pick the modules you want to try. These can be changed later.',
        'modules_unavailable': 'The module list is unavailable right now. We will enable the core modules for your trial.',
        'modules_none_selected': 'No modules selected yet.',
        'lookup_unavailable': 'List unavailable',
        'select_country_first': 'Select a country first',
        'select_state_first': 'Select a state first',
        'creating_your_trial': 'Creating your trial...',
        'start_my_free_trial': 'Start My Free Trial',
        'passwords_do_not_match': 'Passwords do not match',
        'password_too_short': 'Password must be at least 8 characters',
        'field_required': 'This field is required',
        'trial_ready_title': 'Your trial is ready!',
        'trial_ready_body': 'We created {name}. Sign in with the username {user}.',
        'trial_ready_expiry': 'Your trial ends on {date}, {days} days from today.',
        'trial_redirecting': 'Taking you to the login page in {seconds} seconds...',
        'go_to_login': 'Go to Login',
        'back_to_home': 'Back to Home',
        'select_org_for_trial': 'Choose your organization type to start your {days}-day free trial.',
    },
    'Urdu': {
        'welcome': 'EDXS میں خوش آمدید',
        'select_org': 'آگے بڑھنے کے لیے براہ کرم اپنی تنظیم کی قسم منتخب کریں۔',
        'enterprise_solutions': 'انٹرپرائز سلوشنز v3.0',
        'change_language': 'زبان تبدیل کریں',
        'save': 'محفوظ کریں',
        'cancel': 'منسوخ کریں',
        'select_language': 'زبان منتخب کریں۔',
        'school': 'اسکول',
        'school_subtitle': 'K-12 ایجوکیشن سویٹ',
        'school_desc': 'طلباء، امتحانات، اور روزانہ کی حاضری کا جامع انتظام۔',
        'college': 'کالج',
        'college_subtitle': 'تعلیمی اور پیشہ ورانہ',
        'college_desc': 'داخلے، فیکلٹی ورک فلوز، اور کورس کے شیڈول کو ہموار کریں۔',
        'university': 'یونیورسٹی',
        'univ_subtitle': 'گلوبل کیمپس ERP',
        'univ_desc': 'ملٹی کیمپس ریسرچ اور ایڈمنسٹریشن کے لیے جدید اتحاد۔',
        'training': 'پیشہ ورانہ تربیت',
        'training_subtitle': 'پیشہ ورانہ مہارت',
        'training_desc': 'کارپوریٹ ٹریننگ اور سکل ڈویلپمنٹ سینٹرز کے لیے جدید ورک فلوز۔',
        'corporate': 'کارپوریٹ سلوشنز',
        'corp_subtitle': 'انٹرپرائز بزنس سویٹ',
        'corp_desc': 'افرادی قوت کی تربیت، کارپوریٹ اکیڈمیوں، اور کاروباری کارروائیوں کے لیے قابل توسیع انتظام۔',
        'enter_module': 'ماڈیول درج کریں۔',
        'back_to_selection': 'سلیکشن پر واپس جائیں۔',
        'back': 'پیچھے',
        'next': 'اگلے',
        'basic_information': 'بنیادی معلومات',
        'please_provide_the_following_details_to_set_up_your': 'براہ کرم اپنے سیٹ اپ کرنے کے لیے درج ذیل تفصیلات فراہم کریں',
        'contact_person_name': 'رابطہ کرنے والے شخص کا نام',
        'designation': 'عہدہ',
        'email_address': 'ای میل ایڈریس',
        'cell_phone_number': 'سیل فون نمبر',
        'landline_number': 'لینڈ لائن نمبر',
        'website': 'ویب سائٹ',
        'address': 'پتہ',
        'street_address': 'گھر کا پتہ',
        'city': 'شہر',
        'state_province': 'صوبہ / ریاست',
        'postal_code': 'پوسٹل کوڈ',
        'karachi': 'کراچی',
        'sindh': 'سندھ',
        '75500': '75500',
        'organization_setup': 'تنظیم کا سیٹ اپ',
        'configure_the_core_settings_and_branding_for_your': 'بنیادی ترتیبات اور برانڈنگ کی ترتیب دیں۔',
        'core_settings': 'بنیادی ترتیبات',
        'organization_code': 'تنظیمی کوڈ',
        'fiscal_year': 'مالی سال',
        'curriculum': 'نصاب',
        'curriculum_placeholder': 'مثال کے طور پر او لیولز، ایس ایس سی، کیمبرج',
        'affiliation_board': 'الحاق بورڈ',
        'affiliation_placeholder': 'مثال کے طور پر BIEK، BISE',
        'hec_id_registration_no': 'HEC ID / رجسٹریشن نمبر',
        'hec_id_placeholder': 'مثال کے طور پر UNIV-2024-001',
        'branding': 'برانڈنگ',
        'upload_logo': 'لوگو اپ لوڈ کریں۔',
        'drag_and_drop_your_logo_here': 'اپنا لوگو یہاں گھسیٹیں اور چھوڑیں',
        'or_click_to_browse': 'یا براؤز کرنے کے لیے کلک کریں۔',
        'drag_and_drop_or_click_to_browse': 'گھسیٹ کر چھوڑیں، یا براؤز کرنے کے لیے کلک کریں۔',
        'supported_formats': 'تائید شدہ فارمیٹس: PNG, JPG (زیادہ سے زیادہ 2MB)',
        'remove_logo': 'لوگو ہٹائیں',
        'click_to_change_logo': 'لوگو تبدیل کرنے کے لیے کلک کریں۔',
        'complete_setup': 'سیٹ اپ مکمل کریں',
        'all_set': 'سب تیار ہے!',
        'configuration_complete': 'ترتیب مکمل ہو گئی!',
        'your_organization_has_been_successfully_configured': 'آپ کی تنظیم کامیابی کے ساتھ کنفیگر ہو گئی ہے۔',
        'details': 'تفصیلات',
        'information': 'معلومات',
        'name': 'نام',
        'all_rights_reserved': 'جملہ حقوق محفوظ ہیں۔',
        'key_features': 'اہم خصوصیات',
        'visibility': 'نمایاں ہونا',
        'branding_logo': 'لوگو اور برانڈنگ',
        'please_fill_required_fields': 'براہ کرم مطلوبہ فیلڈز کو صحیح طریقے سے پُر کریں۔',
        'valid_email_address': 'درست ای میل ایڈریس',
        'redirecting_to_dashboard': 'ڈیش بورڈ پر ری ڈائریکٹ ہو رہا ہے...',
        'redirecting_to_selection': 'سلیکشن پر ری ڈائریکٹ ہو رہا ہے...',
        'validation_required': 'تصدیق درکار ہے۔',
        'select_our': 'منتخب کریں اپنے',
        'organization_type': 'ادارے کی قسم',
        'get_started_desc': 'شروع کرنے کے لیے وہ سیٹ اپ منتخب کریں جو آپ کے ادارے سے میل کھاتا ہو۔',
        'start_your_free_trial': 'اپنا مفت ٹرائل شروع کریں',
        'trial_form_intro': 'اپنا ادارہ اور لاگ اِن بنائیں۔ سیٹ اپ میں ایک منٹ لگتا ہے، کریڈٹ کارڈ کی ضرورت نہیں۔',
        'trial_disclaimer_title': '{days} دن کا مفت ٹرائل',
        'trial_disclaimer_body': 'یہ {days} دن کا مفت ٹرائل اکاؤنٹ ہے جو {date} کو ختم ہو جائے گا۔ اس کے بعد جاری رکھنے کے لیے ہم سے رابطہ کریں۔ ٹرائل کے دوران اصل ڈیٹا درج نہ کریں۔',
        'trial_footer_note': 'شروع کرنے سے آپ تسلیم کرتے ہیں کہ یہ {days} دن کا ٹرائل ہے۔',
        'organization_details': 'ادارے کی تفصیلات',
        'contact_detail': 'رابطے کی تفصیل',
        'your_login': 'آپ کا لاگ اِن',
        'your_login_hint': 'ٹرائل بننے کے بعد آپ انہی تفصیلات سے EDXS میں داخل ہوں گے۔',
        'client_name': 'ادارے کا نام',
        'client_name_placeholder': 'مثلاً ہورائزن اسکول',
        'campus_name': 'کیمپس کا نام',
        'campus_name_placeholder': 'مثلاً مین کیمپس',
        'description': 'تفصیل',
        'contact_person': 'رابطہ کرنے والا شخص',
        'contact_no': 'رابطہ نمبر',
        'mobile': 'موبائل',
        'country': 'ملک',
        'state': 'صوبہ',
        'username': 'صارف نام',
        'password': 'پاس ورڈ',
        'confirm_password': 'پاس ورڈ کی تصدیق',
        'full_name': 'پورا نام',
        'show_password': 'پاس ورڈ دکھائیں',
        'hide_password': 'پاس ورڈ چھپائیں',
        'module_access': 'ماڈیولز',
        'module_access_hint': 'جو ماڈیولز آزمانا چاہتے ہیں منتخب کریں۔ بعد میں تبدیل کیے جا سکتے ہیں۔',
        'modules_unavailable': 'ماڈیولز کی فہرست ابھی دستیاب نہیں۔ ہم آپ کے ٹرائل کے لیے بنیادی ماڈیولز فعال کر دیں گے۔',
        'modules_none_selected': 'ابھی کوئی ماڈیول منتخب نہیں کیا گیا۔',
        'lookup_unavailable': 'فہرست دستیاب نہیں',
        'select_country_first': 'پہلے ملک منتخب کریں',
        'select_state_first': 'پہلے صوبہ منتخب کریں',
        'creating_your_trial': 'آپ کا ٹرائل بنایا جا رہا ہے...',
        'start_my_free_trial': 'میرا مفت ٹرائل شروع کریں',
        'passwords_do_not_match': 'پاس ورڈ آپس میں میل نہیں کھاتے',
        'password_too_short': 'پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے',
        'field_required': 'یہ خانہ ضروری ہے',
        'trial_ready_title': 'آپ کا ٹرائل تیار ہے!',
        'trial_ready_body': 'ہم نے {name} بنا دیا ہے۔ صارف نام {user} سے لاگ اِن کریں۔',
        'trial_ready_expiry': 'آپ کا ٹرائل {date} کو ختم ہوگا، آج سے {days} دن بعد۔',
        'trial_redirecting': '{seconds} سیکنڈ میں آپ کو لاگ اِن پیج پر لے جایا جا رہا ہے...',
        'go_to_login': 'لاگ اِن پر جائیں',
        'back_to_home': 'ہوم پر واپس',
        'select_org_for_trial': '{days} دن کا مفت ٹرائل شروع کرنے کے لیے اپنے ادارے کی قسم منتخب کریں۔',
    },
    'Arabic': {
        'welcome': 'مرحباً بكم في EDXS',
        'select_org': 'يرجى اختيار نوع مؤسستك للمتابعة',
        'enterprise_solutions': 'حلول المؤسسات v3.0',
        'change_language': 'تغيير اللغة',
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'select_language': 'اختار اللغة',
        'school': 'مدرسة',
        'school_subtitle': 'جناح التعليم K-12',
        'school_desc': 'إدارة شاملة للطلاب والامتحانات والحضور اليومي.',
        'college': 'كلية',
        'college_subtitle': 'أكاديمي ومهني',
        'college_desc': 'تبسيط القبول وسير عمل أعضاء هيئة التدريس وجدولة الدورات.',
        'university': 'جامعة',
        'univ_subtitle': 'ERP الحرم الجامعي العالمي',
        'univ_desc': 'توحيد متقدم للبحوث والإدارة متعددة الحرم الجامعي.',
        'training': 'تدريب مهني',
        'training_subtitle': 'المهنية والمهارات',
        'training_desc': 'سير عمل متقدم للتدريب المؤسسي ومراكز تطوير المهارات.',
        'corporate': 'حلول الشركات',
        'corp_subtitle': 'مجموعة أعمال المؤسسات',
        'corp_desc': 'إدارة قابلة للتوسع لتدريب القوى العاملة، وأكاديميات الشركات، وعمليات الأعمال.',
        'enter_module': 'أدخل الوحدة',
        'back_to_selection': 'العودة إلى التحديد',
        'back': 'رجوع',
        'next': 'التالي',
        'basic_information': 'معلومات أساسية',
        'please_provide_the_following_details_to_set_up_your': 'يرجى تقديم التفاصيل التالية لإعداد',
        'contact_person_name': 'اسم جهة الاتصال',
        'designation': 'المسمى الوظيفي',
        'email_address': 'عنوان البريد الإلكتروني',
        'cell_phone_number': 'رقم الجوال',
        'landline_number': 'رقم الهاتف الأرضي',
        'website': 'الموقع الإلكتروني',
        'address': 'العنوان',
        'street_address': 'عنوان الشارع',
        'city': 'المدينة',
        'state_province': 'الولاية / المقاطعة',
        'postal_code': 'الرمز البريدي',
        'karachi': 'كراتشي',
        'sindh': 'السند',
        '75500': '75500',
        'organization_setup': 'إعداد المنظمة',
        'configure_the_core_settings_and_branding_for_your': 'تكوين الإعدادات الأساسية والعلامة التجارية لـ',
        'core_settings': 'الإعدادات الأساسية',
        'organization_code': 'كود المنظمة',
        'fiscal_year': 'السنة المالية',
        'curriculum': 'المنهج الدراسي',
        'curriculum_placeholder': 'مثلاً: O-Levels, SSC, Cambridge',
        'affiliation_board': 'مجلس الانتماء',
        'affiliation_placeholder': 'مثلاً: BIEK, BISE',
        'hec_id_registration_no': 'رقم التسجيل لدى HEC',
        'hec_id_placeholder': 'مثلاً: UNIV-2024-001',
        'branding': 'العلامة التجارية',
        'upload_logo': 'تحميل الشعار',
        'drag_and_drop_your_logo_here': 'قم بسحب وإسقاط شعارك هنا',
        'or_click_to_browse': 'أو انقر للتصفح',
        'drag_and_drop_or_click_to_browse': 'اسحب وأفلت، أو انقر للتصفح',
        'supported_formats': 'التنسيقات المدعومة: PNG, JPG (بحد أقصى 2 ميجابايت)',
        'remove_logo': 'إزالة الشعار',
        'click_to_change_logo': 'انقر لتغيير الشعار',
        'complete_setup': 'إكمال الإعداد',
        'all_set': 'كل شيء جاهز!',
        'configuration_complete': 'اكتمل التكوين!',
        'your_organization_has_been_successfully_configured': 'تم تكوين منظمتك بنجاح.',
        'details': 'تفاصيل',
        'information': 'معلومات',
        'name': 'اسم',
        'all_rights_reserved': 'جميع الحقوق محفوظة.',
        'key_features': 'الميزات الرئيسية',
        'visibility': 'الرؤية',
        'branding_logo': 'الشعار والعلامة التجارية',
        'please_fill_required_fields': 'يرجى ملء الحقول المطلوبة بشكل صحيح',
        'valid_email_address': 'عنوان بريد إلكتروني صالح',
        'redirecting_to_dashboard': 'جارٍ إعادة التوجيه إلى لوحة القيادة...',
        'redirecting_to_selection': 'جارٍ إعادة التوجيه إلى التحديد...',
        'validation_required': 'التحقق مطلوب',
        'select_our': 'اختر نوع',
        'organization_type': 'مؤسستك',
        'get_started_desc': 'اختر الإعداد الذي يناسب مؤسستك للبدء.',
        'start_your_free_trial': 'ابدأ تجربتك المجانية',
        'trial_form_intro': 'أنشئ حساب مؤسستك وسجّل الدخول. الإعداد يستغرق دقيقة واحدة، ولا حاجة لبطاقة ائتمان.',
        'trial_disclaimer_title': 'تجربة مجانية لمدة {days} يوماً',
        'trial_disclaimer_body': 'هذا حساب تجريبي مجاني مدته {days} يوماً وينتهي في {date}. للاستمرار بعد ذلك، تواصل معنا لترقية حسابك. لا تُدخل بيانات إنتاجية أثناء التجربة.',
        'trial_footer_note': 'بالبدء تقرّ بأن هذه تجربة مدتها {days} يوماً.',
        'organization_details': 'تفاصيل المؤسسة',
        'contact_detail': 'بيانات الاتصال',
        'your_login': 'بيانات الدخول',
        'your_login_hint': 'هذه هي بيانات دخولك إلى EDXS بعد إنشاء التجربة.',
        'client_name': 'اسم المؤسسة',
        'client_name_placeholder': 'مثلاً: مدرسة الأفق',
        'campus_name': 'اسم الحرم',
        'campus_name_placeholder': 'مثلاً: الحرم الرئيسي',
        'description': 'الوصف',
        'contact_person': 'جهة الاتصال',
        'contact_no': 'رقم الاتصال',
        'mobile': 'الجوال',
        'country': 'الدولة',
        'state': 'الولاية',
        'username': 'اسم المستخدم',
        'password': 'كلمة المرور',
        'confirm_password': 'تأكيد كلمة المرور',
        'full_name': 'الاسم الكامل',
        'show_password': 'إظهار كلمة المرور',
        'hide_password': 'إخفاء كلمة المرور',
        'module_access': 'الوحدات',
        'module_access_hint': 'اختر الوحدات التي تريد تجربتها. يمكن تغييرها لاحقاً.',
        'modules_unavailable': 'قائمة الوحدات غير متاحة حالياً. سنفعّل الوحدات الأساسية لتجربتك.',
        'modules_none_selected': 'لم تختر أي وحدة بعد.',
        'lookup_unavailable': 'القائمة غير متاحة',
        'select_country_first': 'اختر الدولة أولاً',
        'select_state_first': 'اختر الولاية أولاً',
        'creating_your_trial': 'جارٍ إنشاء التجربة...',
        'start_my_free_trial': 'ابدأ تجربتي المجانية',
        'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
        'password_too_short': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
        'field_required': 'هذا الحقل مطلوب',
        'trial_ready_title': 'تجربتك جاهزة!',
        'trial_ready_body': 'أنشأنا {name}. سجّل الدخول باسم المستخدم {user}.',
        'trial_ready_expiry': 'تنتهي تجربتك في {date}، بعد {days} يوماً من اليوم.',
        'trial_redirecting': 'سيتم نقلك إلى صفحة تسجيل الدخول خلال {seconds} ثانية...',
        'go_to_login': 'الذهاب إلى تسجيل الدخول',
        'back_to_home': 'العودة إلى الرئيسية',
        'select_org_for_trial': 'اختر نوع مؤسستك لبدء التجربة المجانية لمدة {days} يوماً.',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('English');

    const t = useCallback((key: string, vars?: Record<string, string>) => {
        const phrase = translations[language][key] || key;
        if (!vars) return phrase;

        // An unknown placeholder is left as written rather than blanked, so a
        // missing variable shows up as `{days}` instead of a silent gap.
        return phrase.replace(/\{(\w+)\}/g, (match, name: string) => vars[name] ?? match);
    }, [language]);

    // Memoised so consumers re-render when the language actually changes, not
    // every time this provider happens to render.
    const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

    return (
        <LanguageContext.Provider value={value}>
            <Box sx={{ direction: language === 'English' ? 'ltr' : 'rtl' }}>
                {children}
            </Box>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

