import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';
import { Box } from '@mui/material';

type Language = 'English' | 'Urdu' | 'Arabic';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    'English': {
        'welcome': 'Welcome to EDXS',
        'select_org': 'Please select your organization type to proceed',
        'enterprise_solutions': 'Enterprise Solutions v3.0',
        'change_language': 'Change Language',
        'save': 'Save',
        'cancel': 'Cancel',
        'select_language': 'Select Language',
        'school': 'School',
        'school_subtitle': 'K-12 Education Suite',
        'school_desc': 'Comprehensive management for students, exams, and daily attendance.',
        'college': 'College',
        'college_subtitle': 'Academic & Vocational',
        'college_desc': 'Streamline admissions, faculty workflows, and course scheduling.',
        'university': 'University',
        'univ_subtitle': 'Global Campus ERP',
        'univ_desc': 'Advanced unification for multi-campus research and administration.',
        'training': 'Professional Training',
        'training_subtitle': 'Vocational & Skills',
        'training_desc': 'Advanced workflows for corporate training and skill development centers.',
        'corporate': 'Corporate Solutions',
        'corp_subtitle': 'Enterprise Business Suite',
        'corp_desc': 'Scalable management for workforce training, corporate academies, and business operations.',
        'enter_module': 'ENTER MODULE',
        'back_to_selection': 'Back to Selection',
        'back': 'Back',
        'next': 'Next',
        'basic_information': 'Basic Information',
        'please_provide_the_following_details_to_set_up_your': 'Please provide the following details to set up your',
        'contact_person_name': 'Contact Person Name',
        'designation': 'Designation',
        'email_address': 'Email Address',
        'cell_phone_number': 'Cell Phone Number',
        'landline_number': 'Landline Number',
        'website': 'Website',
        'address': 'Address',
        'street_address': 'Street Address',
        'city': 'City',
        'state_province': 'State/Province',
        'postal_code': 'Postal Code',
        'karachi': 'Karachi',
        'sindh': 'Sindh',
        '75500': '75500',
        'organization_setup': 'Organization Setup',
        'configure_the_core_settings_and_branding_for_your': 'Configure the core settings and branding for your',
        'core_settings': 'Core Settings',
        'organization_code': 'Organization Code',
        'fiscal_year': 'Fiscal Year',
        'curriculum': 'Curriculum',
        'curriculum_placeholder': 'e.g. O-Levels, SSC, Cambridge',
        'affiliation_board': 'Affiliation Board',
        'affiliation_placeholder': 'e.g. BIEK, BISE',
        'hec_id_registration_no': 'HEC ID / Registration No.',
        'hec_id_placeholder': 'e.g. UNIV-2024-001',
        'branding': 'Branding',
        'upload_logo': 'Upload Logo',
        'drag_and_drop_your_logo_here': 'Drag and drop your logo here',
        'or_click_to_browse': 'or click to browse',
        'supported_formats': 'Supported formats: PNG, JPG (Max 2MB)',
        'remove_logo': 'Remove Logo',
        'click_to_change_logo': 'Click to change logo',
        'complete_setup': 'Complete Setup',
        'all_set': 'All Set!',
        'configuration_complete': 'Configuration Complete!',
        'your_organization_has_been_successfully_configured': 'Your organization has been successfully configured.',
        'details': 'Details',
        'information': 'Information',
        'name': 'Name',
        'all_rights_reserved': 'All rights reserved',
        'key_features': 'Key Features',
        'visibility': 'Visibility',
        'branding_logo': 'Logo & Branding',
        'please_fill_required_fields': 'Please fill in the required fields correctly',
        'valid_email_address': 'Valid Email Address',
        'redirecting_to_dashboard': 'Redirecting to dashboard...',
        'redirecting_to_selection': 'Redirecting to selection...',
        'validation_required': 'Validation Required',
    },
    'Urdu': {
        'welcome': 'EDXS میں خوش آمدید',
        'select_org': 'آگے بڑھنے کے لیے براہ کرم اپنی تنظیم کی قسم منتخب کریں۔',
        'enterprise_solutions': 'انٹرپرائز سلوشنز v3.0',
        'change_language': 'زبان تبدیل کریں',
        'save': 'محفوظ کریں',
        'cancel': 'منسوخ کریں',
        'select_language': 'زبان منتخب کریں۔',
        'school': 'اسکول',
        'school_subtitle': 'K-12 ایجوکیشن سویٹ',
        'school_desc': 'طلباء، امتحانات، اور روزانہ کی حاضری کا جامع انتظام۔',
        'college': 'کالج',
        'college_subtitle': 'تعلیمی اور پیشہ ورانہ',
        'college_desc': 'داخلے، فیکلٹی ورک فلوز، اور کورس کے شیڈول کو ہموار کریں۔',
        'university': 'یونیورسٹی',
        'univ_subtitle': 'گلوبل کیمپس ERP',
        'univ_desc': 'ملٹی کیمپس ریسرچ اور ایڈمنسٹریشن کے لیے جدید اتحاد۔',
        'training': 'پیشہ ورانہ تربیت',
        'training_subtitle': 'پیشہ ورانہ مہارت',
        'training_desc': 'کارپوریٹ ٹریننگ اور سکل ڈویلپمنٹ سینٹرز کے لیے جدید ورک فلوز۔',
        'corporate': 'کارپوریٹ سلوشنز',
        'corp_subtitle': 'انٹرپرائز بزنس سویٹ',
        'corp_desc': 'افرادی قوت کی تربیت، کارپوریٹ اکیڈمیوں، اور کاروباری کارروائیوں کے لیے قابل توسیع انتظام۔',
        'enter_module': 'ماڈیول درج کریں۔',
        'back_to_selection': 'سلیکشن پر واپس جائیں۔',
        'back': 'پیچھے',
        'next': 'اگلے',
        'basic_information': 'بنیادی معلومات',
        'please_provide_the_following_details_to_set_up_your': 'براہ کرم اپنے سیٹ اپ کرنے کے لیے درج ذیل تفصیلات فراہم کریں',
        'contact_person_name': 'رابطہ کرنے والے شخص کا نام',
        'designation': 'عہدہ',
        'email_address': 'ای میل ایڈریس',
        'cell_phone_number': 'سیل فون نمبر',
        'landline_number': 'لینڈ لائن نمبر',
        'website': 'ویب سائٹ',
        'address': 'پتہ',
        'street_address': 'گھر کا پتہ',
        'city': 'شہر',
        'state_province': 'صوبہ / ریاست',
        'postal_code': 'پوسٹل کوڈ',
        'karachi': 'کراچی',
        'sindh': 'سندھ',
        '75500': '75500',
        'organization_setup': 'تنظیم کا سیٹ اپ',
        'configure_the_core_settings_and_branding_for_your': 'بنیادی ترتیبات اور برانڈنگ کی ترتیب دیں۔',
        'core_settings': 'بنیادی ترتیبات',
        'organization_code': 'تنظیمی کوڈ',
        'fiscal_year': 'مالی سال',
        'curriculum': 'نصاب',
        'curriculum_placeholder': 'مثال کے طور پر او لیولز، ایس ایس سی، کیمبرج',
        'affiliation_board': 'الحاق بورڈ',
        'affiliation_placeholder': 'مثال کے طور پر BIEK، BISE',
        'hec_id_registration_no': 'HEC ID / رجسٹریشن نمبر',
        'hec_id_placeholder': 'مثال کے طور پر UNIV-2024-001',
        'branding': 'برانڈنگ',
        'upload_logo': 'لوگو اپ لوڈ کریں۔',
        'drag_and_drop_your_logo_here': 'اپنا لوگو یہاں گھسیٹیں اور چھوڑیں',
        'or_click_to_browse': 'یا براؤز کرنے کے لیے کلک کریں۔',
        'supported_formats': 'تائید شدہ فارمیٹس: PNG, JPG (زیادہ سے زیادہ 2MB)',
        'remove_logo': 'لوگو ہٹائیں',
        'click_to_change_logo': 'لوگو تبدیل کرنے کے لیے کلک کریں۔',
        'complete_setup': 'سیٹ اپ مکمل کریں',
        'all_set': 'سب تیار ہے!',
        'configuration_complete': 'ترتیب مکمل ہو گئی!',
        'your_organization_has_been_successfully_configured': 'آپ کی تنظیم کامیابی کے ساتھ کنفیگر ہو گئی ہے۔',
        'details': 'تفصیلات',
        'information': 'معلومات',
        'name': 'نام',
        'all_rights_reserved': 'جملہ حقوق محفوظ ہیں۔',
        'key_features': 'اہم خصوصیات',
        'visibility': 'نمایاں ہونا',
        'branding_logo': 'لوگو اور برانڈنگ',
        'please_fill_required_fields': 'براہ کرم مطلوبہ فیلڈز کو صحیح طریقے سے پُر کریں۔',
        'valid_email_address': 'درست ای میل ایڈریس',
        'redirecting_to_dashboard': 'ڈیش بورڈ پر ری ڈائریکٹ ہو رہا ہے...',
        'redirecting_to_selection': 'سلیکشن پر ری ڈائریکٹ ہو رہا ہے...',
        'validation_required': 'تصدیق درکار ہے۔',
    },
    'Arabic': {
        'welcome': 'مرحباً بكم في EDXS',
        'select_org': 'يرجى اختيار نوع مؤسستك للمتابعة',
        'enterprise_solutions': 'حلول المؤسسات v3.0',
        'change_language': 'تغيير اللغة',
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'select_language': 'اختار اللغة',
        'school': 'مدرسة',
        'school_subtitle': 'جناح التعليم K-12',
        'school_desc': 'إدارة شاملة للطلاب والامتحانات والحضور اليومي.',
        'college': 'كلية',
        'college_subtitle': 'أكاديمي ومهني',
        'college_desc': 'تبسيط القبول وسير عمل أعضاء هيئة التدريس وجدولة الدورات.',
        'university': 'جامعة',
        'univ_subtitle': 'ERP الحرم الجامعي العالمي',
        'univ_desc': 'توحيد متقدم للبحوث والإدارة متعددة الحرم الجامعي.',
        'training': 'تدريب مهني',
        'training_subtitle': 'المهنية والمهارات',
        'training_desc': 'سير عمل متقدم للتدريب المؤسسي ومراكز تطوير المهارات.',
        'corporate': 'حلول الشركات',
        'corp_subtitle': 'مجموعة أعمال المؤسسات',
        'corp_desc': 'إدارة قابلة للتوسع لتدريب القوى العاملة، وأكاديميات الشركات، وعمليات الأعمال.',
        'enter_module': 'أدخل الوحدة',
        'back_to_selection': 'العودة إلى التحديد',
        'back': 'رجوع',
        'next': 'التالي',
        'basic_information': 'معلومات أساسية',
        'please_provide_the_following_details_to_set_up_your': 'يرجى تقديم التفاصيل التالية لإعداد',
        'contact_person_name': 'اسم جهة الاتصال',
        'designation': 'المسمى الوظيفي',
        'email_address': 'عنوان البريد الإلكتروني',
        'cell_phone_number': 'رقم الجوال',
        'landline_number': 'رقم الهاتف الأرضي',
        'website': 'الموقع الإلكتروني',
        'address': 'العنوان',
        'street_address': 'عنوان الشارع',
        'city': 'المدينة',
        'state_province': 'الولاية / المقاطعة',
        'postal_code': 'الرمز البريدي',
        'karachi': 'كراتشي',
        'sindh': 'السند',
        '75500': '75500',
        'organization_setup': 'إعداد المنظمة',
        'configure_the_core_settings_and_branding_for_your': 'تكوين الإعدادات الأساسية والعلامة التجارية لـ',
        'core_settings': 'الإعدادات الأساسية',
        'organization_code': 'كود المنظمة',
        'fiscal_year': 'السنة المالية',
        'curriculum': 'المنهج الدراسي',
        'curriculum_placeholder': 'مثلاً: O-Levels, SSC, Cambridge',
        'affiliation_board': 'مجلس الانتماء',
        'affiliation_placeholder': 'مثلاً: BIEK, BISE',
        'hec_id_registration_no': 'رقم التسجيل لدى HEC',
        'hec_id_placeholder': 'مثلاً: UNIV-2024-001',
        'branding': 'العلامة التجارية',
        'upload_logo': 'تحميل الشعار',
        'drag_and_drop_your_logo_here': 'قم بسحب وإسقاط شعارك هنا',
        'or_click_to_browse': 'أو انقر للتصفح',
        'supported_formats': 'التنسيقات المدعومة: PNG, JPG (بحد أقصى 2 ميجابايت)',
        'remove_logo': 'إزالة الشعار',
        'click_to_change_logo': 'انقر لتغيير الشعار',
        'complete_setup': 'إكمال الإعداد',
        'all_set': 'كل شيء جاهز!',
        'configuration_complete': 'اكتمل التكوين!',
        'your_organization_has_been_successfully_configured': 'تم تكوين منظمتك بنجاح.',
        'details': 'تفاصيل',
        'information': 'معلومات',
        'name': 'اسم',
        'all_rights_reserved': 'جميع الحقوق محفوظة.',
        'key_features': 'الميزات الرئيسية',
        'visibility': 'الرؤية',
        'branding_logo': 'الشعار والعلامة التجارية',
        'please_fill_required_fields': 'يرجى ملء الحقول المطلوبة بشكل صحيح',
        'valid_email_address': 'عنوان بريد إلكتروني صالح',
        'redirecting_to_dashboard': 'جارٍ إعادة التوجيه إلى لوحة القيادة...',
        'redirecting_to_selection': 'جارٍ إعادة التوجيه إلى التحديد...',
        'validation_required': 'التحقق مطلوب',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('English');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            <Box sx={{ direction: language === 'English' ? 'ltr' : 'rtl' }}>
                {children}
            </Box>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

